version: '3'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - auth
      - tutorial
    ports:
      - 8083:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - auth:/var/www/auth
      - tutorial:/var/www/tutorial
  
  auth:
    container_name: authentication_ui
    build:
      context: authentication-ui
      dockerfile: Dockerfile
    volumes:
      - auth:/app/build

  tutorial:
    container_name: reward_tutorial
    build:
      context: reward_tutorial
      dockerfile: Dockerfile
    volumes:
      - tutorial:/app/dist
  
  authentication_server_db:
    container_name: authentication_server_db
    image: mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=authroot
    volumes:
      - ./authentication-server/db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  auth-server:
    container_name: auth-server
    depends_on:
      - authentication_server_db
      - redis
    restart: on-failure
    build:
      context: authentication-server
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      - SECRET_KEY=secret
      - MYSQL_PASSWORD=authroot
  

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  
volumes:
  auth:
  tutorial:
