CREATE DATABASE app_users;
USE app_users;

CREATE TABLE IF NOT EXISTS users (id VARCHAR(32) PRIMARY KEY UNIQUE, email VARCHAR(345) UNIQUE, password VARCHAR(1024) NOT NULL, user_role VARCHAR(32) NOT NULL);
